#!/usr/bin/env bash

# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
echo "Page you are looking for is not here" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;/error_page custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx reload