#!/usr/bin/env bash

# Install and configure HAproxy on your lb-01 server.

load_balancer_config= "\
frontend http-in
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    option httpchk GET /health_check
    http-check expect status 200
    server web-01
    server web-02
"
sudo apt-get -y update
sudo apt-get install -y software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get install -y haproxy
cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo "$load_balancer_config" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
