#!/bin/bash
# Fix the web server so that it is running as the nginx user.
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user www-data/user nginx\n    group nginx/' /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080\n    listen [::]:8080/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
